version: '3.4'
services:
  app:
    image: urlshortener
    build: ./
    user: 'root:root'
    ports:
      - 3000:3000
    depends_on:
      - pg
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SERVER_BASEURL: ${SERVER_BASEURL}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
  pg:
    image: postgres:11.9
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_HOST: ${DB_HOST}