version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: userway
    container_name: userway
    restart: unless-stopped
    env_file: .env
    environment:
      - SERVER_PORT=$SERVER_PORT
      - SERVER_BASEURL=$SERVER_BASEURL
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network